name: spark-livy-on-airflow-workspace
channels:
  - defaults
dependencies:
  - ca-certificates=2021.1.19=hecd8cb5_1
  - certifi=2020.12.5=py36hecd8cb5_0
  - libcxx=10.0.0=1
  - libffi=3.3=hb1e8313_2
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1k=h9ed2024_0
  - pip=21.0.1=py36hecd8cb5_0
  - python=3.6.13=h88f2d9e_0
  - readline=8.1=h9ed2024_0
  - setuptools=52.0.0=py36hecd8cb5_0
  - sqlite=3.35.2=hce871da_0
  - tk=8.6.10=hb0a8c7a_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - appdirs==1.4.4
    - appnope==0.1.2
    - backcall==0.2.0
    - black==20.8b1
    - cfgv==3.2.0
    - chardet==3.0.4
    - click==7.1.2
    - dataclasses==0.8
    - decorator==4.4.2
    - distlib==0.3.1
    - filelock==3.0.12
    - identify==2.2.2
    - idna==2.10
    - importlib-metadata==3.9.0
    - importlib-resources==5.1.2
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - mypy-extensions==0.4.3
    - nodeenv==1.5.0
    - parso==0.8.1
    - pathspec==0.8.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pre-commit==2.11.1
    - prompt-toolkit==3.0.18
    - ptyprocess==0.7.0
    - py4j==0.10.7
    - pygments==2.8.1
    - pyspark==2.4.6
    - pyyaml==5.4.1
    - regex==2021.3.17
    - requests==2.23.0
    - six==1.15.0
    - toml==0.10.2
    - traitlets==4.3.3
    - typed-ast==1.4.2
    - typing-extensions==3.7.4.3
    - urllib3==1.25.11
    - virtualenv==20.4.3
    - wcwidth==0.2.5
    - zipp==3.4.1
